### ISSUE TITLE
Getting a panic while building deps

### ISSUE THREAD

**Issue by palash25** [nacardin/cargo-build-deps#9]
This is the backtrace I got after running `RUST_BACKTRACE=1 cargo-build-deps --release`

```
    Updating crates.io index
thread 'main' panicked at 'failed to parse version from depencency string', src/libcore/option.rs:1188:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::option::expect_failed
             at src/libcore/option.rs:1188
  14: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  15: cargo_build_deps::main
  16: std::rt::lang_start::{{closure}}
  17: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  18: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  20: std::panicking::try
             at src/libstd/panicking.rs:270
  21: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  22: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  23: main
  24: __libc_start_main
  25: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

This is my `Cargo.toml` file

```
[package]
name = "junks"
version = "0.1.0"
authors = ["Palash Nigam <npalash25@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
rand = "0.7.3"
regex = "1.3.4"
rustc-serialize = "0.3.24"
serde = "1.0.104"
```

**Comment by iwismer** [comment]
I'm getting the same error:
```
Step 8/21 : RUN cargo build-deps --release
 ---> Running in 4ebd0a9285d2
    Updating crates.io index
    Updating actix-rt v1.0.0 -> v1.1.0
    Updating bytestring v0.1.4 -> v0.1.5
    Updating h2 v0.2.3 -> v0.2.4
    Updating hermit-abi v0.1.8 -> v0.1.11
    Updating ignore v0.4.13 -> v0.4.14
    Updating libc v0.2.68 -> v0.2.69
    Updating lock_api v0.3.3 -> v0.3.4
    Updating num_cpus v1.12.0 -> v1.13.0
    Updating parking_lot v0.10.0 -> v0.10.2
    Updating parking_lot_core v0.7.0 -> v0.7.1
    Updating pin-project v0.4.8 -> v0.4.9
    Updating pin-project-internal v0.4.8 -> v0.4.9
    Updating proc-macro-hack v0.5.14 -> v0.5.15
    Updating proc-macro2 v1.0.9 -> v1.0.10
    Updating serde_json v1.0.50 -> v1.0.51
    Updating smallvec v1.2.0 -> v1.3.0
    Updating socket2 v0.3.11 -> v0.3.12
    Updating tokio v0.2.17 -> v0.2.18
      Adding tokio-util v0.3.1
    Updating typenum v1.11.2 -> v1.12.0
    Updating winapi-util v0.1.3 -> v0.1.4
thread 'main' panicked at 'failed to parse version from depencency string', src/libcore/option.rs:1185:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::option::expect_failed
             at src/libcore/option.rs:1185
  15: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  16: cargo_build_deps::main
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  21: std::panicking::try
             at src/libstd/panicking.rs:265
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  24: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
The command '/bin/sh -c cargo build-deps --release' returned a non-zero code: 101
```

My dependencies:
```
[dependencies]
actix-files = "0.2.1"
actix-multipart = "0.2.0"
actix-rt = "1.0.0"
actix-web = "2.0.0"
actix-web-httpauth = "0.4.1"
bcrypt = "0.7.0"
bson = "0.14.0"
futures = "0.3.1"
mongodb = "0.9.2"
serde = "^1.0.106"
tera = "1.2.0"
lazy_static = "1.4.0"
regex = "1"
```

**Comment by stevemk14ebr** [comment]
Ditto:

```
Step 8/25 : RUN cargo build-deps --release
 ---> Running in 663e6b279785
    Updating crates.io index
    Updating arc-swap v0.4.5 -> v0.4.6
    Updating built v0.4.0 -> v0.4.1
    Updating cc v1.0.50 -> v1.0.52
    Updating parking_lot_core v0.7.1 -> v0.7.2
    Updating pin-utils v0.1.0-alpha.4 -> v0.1.0
    Updating ryu v1.0.3 -> v1.0.4
    Updating security-framework v0.4.2 -> v0.4.3
    Updating security-framework-sys v0.4.2 -> v0.4.3
    Updating smallvec v1.3.0 -> v1.4.0
    Updating standback v0.2.5 -> v0.2.6
    Updating syn v1.0.17 -> v1.0.18
    Updating threadpool v1.7.1 -> v1.8.0
thread 'main' panicked at 'failed to parse version from depencency string', src/libcore/option.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

```
[package]
build = "build.rs"

[build-dependencies]
built = "^0.4"

[target.'cfg(windows)'.build-dependencies]
winreg = "0.6"

[dependencies]
failure = "^0.1"
# seems to be required for failure
serde_derive = "^1"
serde_json = "^1"
serde = "^1"
csv = "^1"
snap = "^1"
lmdb-rkv = "0.14"
strum = "^0.18"
strum_macros = "^0.18"
byteorder = "^1.3"
human-size = "^0.4"
fnv = "1"
log = "0.4"
simplelog = "^0.7"
tempdir = "0.3"
clap = "2"
sha2 = "^0.8"
regex = "^1"
bytes = "^0.5"
base64 = "0.12"
htmlescape = "0.3"
prometheus = "0.8"
rusoto_core = "0.43.0"
rusoto_s3 = "0.43.0"
rusoto_sns = "0.43.0"
crossbeam-channel = "^0.4"
percent-encoding = "2.1.0"
rustls = "0.16"

actix-web = {version = "2", features=["rustls"]}
actix-rt = "1"
actix-files = "^0.2"

futures = "^0.3"
async-std = "^1.5"
```

**Comment by errmac-v** [comment]
I have this problem too. Seems this is because of parsing `Cargo.lock`. In some cases it doesn't contain version of the package. I don't know if this project is active or not, but I have created another tool based on it https://github.com/errmac-v/cargo-build-dependencies without this issue.

**Comment by stevemk14ebr** [comment]
Fwiw I moved to a solution that doesn't require this tool: https://stackoverflow.com/a/61413980

**Comment by tbarusseau** [comment]
I'm having the same issue as well.

**Comment by tbarusseau** [comment]
So turns out there are several issues:

1. Cargo.toml can contain dependencies with non-semver versions. This is an issue because `cargo build <pkg>:<version>` requires a semver version (I added `cargo metadata` parsing to get a semver version)
2. It always does a `cargo update` for some reason? You don't always want to update dependencies (I added a `--skip-update` flag)
3. It fails to parse versions when the dependency is written like `dep = { version = "<ver>", ... }` (fixed the parsing using @errmac-v's fork)

For anyone who needs a fix now, you can get them with `cargo install cargo-bdeps` (https://github.com/tbarusseau/cargo-build-deps)

I still have one issue to fix before I'll open a PR on this repository, although it doesn't seem to be maintained anymore. We'll see.
